### ISSUE TITLE
The Golan Heights are not in Syria's territory

### ISSUE THREAD

**Issue by amitport** [mledoze/countries#102]

**Comment by herrniemand** [comment]
http://unispal.un.org/UNISPAL.NSF/0/73D6B4C70D1A92B7852560DF0064F101
Resolution 497 (1981)

Adopted by the Security Council at its 2319th meeting
on 17 December 1981

The Security Council,

Having considered the letter of 14 December 1981 from the Permanent Representative of the Syrian Arab Republic contained in document S/14791,

Reaffirming that the acquisition of territory by force is inadmissible, in accordance with the United Nations Charter, the principles of international law, and relevant Security Council resolutions,

1.	Decides that the Israeli decision to impose its laws, jurisdiction and administration in the occupied Syrian Golan Heights is null and void and without international legal effect;

2.	Demands that Israel, the occupying Power, should rescind forthwith its decision;

3.	Determines that all the provisions of the Geneva Convention Relative to the Protection of Civilian Persons in Time of War of 12 August 1949 continue to apply to the Syrian territory occupied by Israel since June 1967;

4.	Requests the Secretary-General to report to the Security Council on the implementation of this resolution within two weeks and decides that in the event of non-compliance by Israel, the Security Council would meet urgently, and not later than 5 January 1982, to consider taking appropriate measures in accordance with the Charter of the United Nations.

**Comment by mledoze** [comment]
@herrniemand do you mean that the GeoJson file for Syria is incorrect?

https://github.com/mledoze/countries/blob/master/data/syr.geo.json

**Comment by herrniemand** [comment]
@mledoze I am saying that despite the fact that de-facto this territory is part of Israel, de-jure it is part of Syria.

**Comment by herrniemand** [comment]
@mledoze It is the same problem as Crimea problem. De-facto is part of Russia, but de-jure it is not. So I this this issue need to be closed as this project's idea based on de-jure facts, rather then de-facto.

**Comment by amitport** [comment]
de-jure, it is disputed, and has been since [1973 Arab–Israeli War - Syrian_atrocities](http://en.wikipedia.org/wiki/Yom_Kippur_War#Syrian_atrocities). You'll find many contradicting _legal_ claims (and with the current Syrian [Nusra](http://en.wikipedia.org/wiki/Al-Nusra_Front)-[ISIS](http://en.wikipedia.org/wiki/Islamic_State_of_Iraq_and_the_Levant)-[Hezbollah](http://en.wikipedia.org/wiki/Hezbollah)-[Assad](http://en.wikipedia.org/wiki/Bashar_al-Assad) situation, there isn't going to be any resolution any time soon).

In any case, the situation is very different from Crimea, as this land was taken during an Arab _attack_ on Israel from several fronts. It is more comparable with [land taken from Germany after WW2](http://en.wikipedia.org/wiki/Territorial_changes_of_Germany_after_World_War_II) and with one additional issue-- giving this land to Syria constitutes an existential threat to Israel.

**Comment by herrniemand** [comment]
@amitport the dispute is not a problem. Problem the fact that Security Council not agrees with Israel position. The same as no one agrees with Russian position. We can not us double standards as it will cause more dispute.

**Comment by herrniemand** [comment]
@amitport if we will change it to Israel the way you see, we will be blamed by anyone else for supporting your position. We are not supporting either position, but simplifying to the point `What UN thinks`.

**Comment by herrniemand** [comment]
@amitport so if UN will say "Hey.```Its Israel territory.```" I will personally push commit to fix it. But till then ignore this minor problem, or fork the project and fix it using http://geojson.io/. Or wait till I fix the issue in my ```visas``` project, and use it.

**Comment by herrniemand** [comment]
@amitport so for now listen to Hadag Nachash! https://www.youtube.com/watch?v=d_S1PNJUcj8

**Comment by amitport** [comment]
:+1: NP

**Comment by herrniemand** [comment]
@amitport since you are from Israel, any suggestions on good bands?*)

**Comment by herrniemand** [comment]
@mledoze I think this issue can be closed.
