### ISSUE TITLE
Missing Country Bonaire

### ISSUE THREAD

**Issue by krisumaru** [mledoze/countries#150]
There is a country Bonaire missing in this data.
https://en.wikipedia.org/wiki/Bonaire
http://mainfacts.com/world-countries-capitals-cities-codes/BQ-BES-Bonaire,-Saint-Eustatius-and-Saba

**Comment by mledoze** [comment]
@krisumaru the country is not missing in the repository, it is here https://github.com/mledoze/countries/blob/8298119ec2468dbcc80f8faba3f59a0d588dd86e/data/bes.divisions.json
It is not in the main `countries.json` file because there are multiple countries with the same ISO 3166-1 alpha-3 code (BES), so these countries have been moved into the `data` folder. The same goes for countries with the SHN country code: https://github.com/mledoze/countries/blob/82dcb4ee04e4dda328d1c28464f7c4f2bc8ba68d/data/shn.divisions.json
