### ISSUE TITLE
Looks like England/Scotland/Northern Ireland/Wales are missing

### ISSUE THREAD

**Issue by cglacet** [mledoze/countries#285]
Is there a reason for these countries to be missing? It looks important to me to have them, I feel like everyone knows them well (except maybe for Wales) and would therefore expect them to "exist" and be part of any application that displays countries. 

If you ask to a random person "in which country is Belfast located?" I'm pretty sure that a vast majority would answer Northern Ireland (or Ireland) before UK.

What is even stranger is the presence of states like "Monaco" for which the term country looks a bit overrated (maybe because I'm French).

**Comment by jjlharrison** [comment]
England, Scotland, and Wales are not sovereign states, Monaco is (and I say that even as an English person).

**Comment by herrjemand** [comment]
Country as UN country. Please refer to official UN list
http://www.un.org/en/member-states/

[image: Ackermann Yuriy] <https://jeman.de/> *Ackermann Yuriy*
Developer
*e:* ackermann.yuriy@gmail.com
*g:* @herrjemand <https://github.com/herrjemand>
*w:* https://jeman.de/

2018-05-04 19:19 GMT+03:00 Christian glacet <notifications@github.com>:

**Comment by curry684** [comment]
Do you really intend to open the can of worms to judge whether a region is country enough in public opinion? Millions of people have died over such debates. 

Stick to the internationally accepted definitions.

**Comment by blumk** [comment]
@cglacet @jjlharrison The official standard is ISO_3166-1 ([ISO](https://www.iso.org/iso-3166-country-codes.html)). This data set is based on ISO-3166-1.

There are 249 official countries – 194 independent & 55 are dependent on other countries. See
see [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1) for details.

**Comment by cglacet** [comment]
I really doubt anyone ever died because of a _json_ file. My point is exactly at the opposite of the debate about whether or not they _are_ countries, my point is **what's the point of having less information**. Also the second argument is **usage > rules** (this is especially true for language and therefore for everything who targets the general public, which is probably your case). The data you are providing have no legal or politic value, that is why you can add whatever you fell is best for the users. If you (personally) think I'm wrong and you think that England is not considered to be a country by the vast majority of people then fine, don't add these countries. But the argument "we can't add them because there are not officially labeled as country" doesn't sound like a real argument for not adding them, especially because you can add a tag to warn people that these countries are not officially recognised as countries (just like you did for independency). This would be the occasion to be even more specific and add labels describing the level of independence (education/transportation/security/...). 

If people are used to refer to some state as a country, even if it's not according to any "authority", then what is the argument for not adding it in the list?

ps: I'm not saying that I don't like what you have done, I'm happy with the data you have here and I'd just like to see them improved on this particular mater.

**Comment by blumk** [comment]
@cglacet ISO stands for _International Organization for Standardization_ and their motto is 

> When the world agrees 

see [ISO](https://www.iso.org/home.html). The world decides in a democratic process what a country is and what not. In any democracy a single individual can and _should_ disagree with the majority, otherwise if no one disagrees you'll have a dictatorship.

This data set follows the ISO-3166-1 specification. If you disagree with ISO for whatever reason, I recommend that you use this official data set and use an abstraction layer in your application and change the entries when importing them.

**Comment by GoGross** [comment]
They colonized the entire world, this collection itself is called Britain

**Comment by curry684** [comment]
> I really doubt anyone ever died because of a json file.

Me too. It's not about the JSON file. It's about whether or not to consider adding disputed territories to a list of countries being used as *authoritative* in tons of online applications, thereby implicitly taking an actual position on that status because it's not backed by any commonly accepted standard.

You are suggesting adding Northern Ireland explicitly. The "territorial dispute" about the status of that region [caused about 1800 deaths](https://en.wikipedia.org/wiki/Provisional_Irish_Republican_Army_campaign#Casualties).

It's the UN's job to worry about such disputes. And ISO's job to package their politics into lists of standards. And this dataset's job is to bring those to software developers.

**Comment by jsgv** [comment]
Will you accept a pull request to add Scotland?

**Comment by blumk** [comment]
@jsgv Scotland is _not_ an independent nor a dependent country. Please refer to the official standard  ISO_3166-1 (ISO). This data set is based on ISO-3166-1.

**Comment by xewl** [comment]
Not to pull this into exaggeration.
Maybe someone could pull in data for the whole ISO 3166-2? (:

**Comment by curry684** [comment]
@xewl that would be pretty much impossible without terrible BC breakage (not going to happen) or terrible data size inflation if adding it as nested properties of their respective countries. Quickly scanning through https://en.wikipedia.org/wiki/ISO_3166-2 I'd estimate the average country has about 25 districts/subregions, thus increasing the dataset's size at least tenfold to include them and a bit of relevant information on them. Also unlikely to happen.

ISO 3166-2 is just a different dataset, it should be a different data source.

**Comment by xewl** [comment]
> ISO 3166-2 is just a different dataset, it should be a different data source.
@curry684 of course that was what I was referring to :)

**Comment by curry684** [comment]
Ah I was interpreting "pull in" as "add to this set" hehe.

**Comment by xewl** [comment]
@écurry684 next to - in relation of - was more my goal there 👍
