### ISSUE TITLE
Great Project I will be usefull to add the nationality of each country

### ISSUE THREAD

**Issue by jcadiba** [mledoze/countries#288]

**Comment by mledoze** [comment]
Hello @jcadiba, the dataset already contains the demonym for each countries; I know that it's not exactly the same thing that the nationality but I fear that adding nationalities would duplicate demonym data.

**Comment by zakjan** [comment]
@mledoze Can we somewhere see in the data, if the country is valid for nationalities? `independent`, maybe?

For example, country French Guiana, demonym Guianan, such nationality doesn't exist, there is only French. This is fine for code to label lookup, but wrong for presenting a list of available options in a select box.

In my projects, after many hours spent trying to answer this, in the end I use country names instead of nationalities.

**Comment by mledoze** [comment]
My "problem" with nationalities is that it's a difficult subject and for now, frankly, I don't know how to solve it elegantly. If you have some ideas, please let me know.

@jcadiba I would suggest to follow the advice from @zakjan, that is the use the country name instead of nationalities, it will work 9/10. What do you think?

**Comment by mtimofiiv** [comment]
Hello, this issue is closed but maybe it's nice to give this some more thought.

I'm not here to start discussions on who should and should not be considered a country. I know it would just be useful to have this data.

Many regions are autonomous or self-governing but fall under another state's de jure or de facto authority. And no case is the same.

American Samoa. The United States of America issues them passports and consider them nationals but not citizens of the country itself ([source](https://en.wikipedia.org/wiki/United_States_passport#Non-citizen_nationals)).

Crimea. Russian Federation issues passports and controls the region but in the GeoJSON, [the territory is in Ukraine](https://github.com/mledoze/countries/blob/master/data/ukr.geo.json).

Northern Cyprus. It has limited recognition as a country (and therefore its passport), but people here are also issued Turkish passports.

I get this is a sensitive subject to some people. Some places involve recent wars, independence movements, etc. **But this should not matter in a dataset.**

So I propose perhaps an elegant way of doing this would be to list who issues the passports of that region. This could be an array with country ISO codes, since for example in the case of N. Cypriots, they would have 2 of them. So...

```js
{
  name: {
    common: 'American Samoa',
    official: 'American Samoa',
    native: { eng: [Object], smo: [Object] }
  },
  tld: [ '.as' ],
  cca2: 'AS',
  ccn3: '016',
  cca3: 'ASM',
  cioc: 'ASA',
  independent: false,
  status: 'officially-assigned',
  currencies: { USD: { name: 'United States dollar', symbol: '$' } },
  idd: { root: '+1', suffixes: [ '684' ] },
  capital: [ 'Pago Pago' ],
  altSpellings: [ 'AS', 'Amerika Sāmoa', 'Amelika Sāmoa', 'Sāmoa Amelika' ],
  region: 'Oceania',
  subregion: 'Polynesia',
  languages: { eng: 'English', smo: 'Samoan' },
  translations: {
    ces: { official: 'Americká Samoa', common: 'Americká Samoa' },
    deu: { official: 'Amerikanisch-Samoa', common: 'Amerikanisch-Samoa' },
    fra: { official: 'Samoa américaines', common: 'Samoa américaines' },
    hrv: { official: 'američka Samoa', common: 'Američka Samoa' },
    ita: { official: 'Samoa americane', common: 'Samoa Americane' },
    jpn: { official: '米サモア', common: 'アメリカ領サモア' },
    nld: { official: 'Amerikaans Samoa', common: 'Amerikaans Samoa' },
    por: { official: 'Samoa americana', common: 'Samoa Americana' },
    rus: { official: 'американское Самоа', common: 'Американское Самоа' },
    slk: { official: 'Americká Samoa', common: 'Americká Samoa' },
    spa: { official: 'Samoa Americana', common: 'Samoa Americana' },
    fin: { official: 'Amerikan Samoa', common: 'Amerikan Samoa' },
    est: { official: 'Ameerika Samoa', common: 'Ameerika Samoa' },
    zho: { official: '美属萨摩亚', common: '美属萨摩亚' },
    pol: { official: 'Samoa Amerykańskie', common: 'Samoa Amerykańskie' },
    urd: { official: 'امریکی سمووا', common: 'امریکی سمووا' },
    kor: { official: '아메리칸사모아', common: '아메리칸사모아' },
    per: { official: 'ساموآی آمریکا', common: 'ساموآی آمریکا' }
  },
  latlng: [ -14.33333333, -170 ],
  landlocked: false,
  borders: [],
  area: 199,
  flag: '🇦🇸',
  demonyms: {
    eng: { f: 'American Samoan', m: 'American Samoan' },
    fra: { f: 'Samoane', m: 'Samoan' }
  },
  passport_issuer: [ 'USA' ]
}
```

```

**Comment by mledoze** [comment]
Hello @mtimofiiv, thank you for the proposition, I like the idea.

Do you know where we can find the data for passport issuers?

**Comment by mtimofiiv** [comment]
Hey @mledoze that's a good question 😉

There is no complete dataset of this that I've been able to find. After doing some research on the subject, I was able to find some very limited data.

Here's some data on what the European Union considers valid passports:
https://www.consilium.europa.eu/prado/en/prado-recognised-documents.html

We can probably discount the fantasy (ie. "Knights of Malta") + obsolete (ie. Zaire).

Funny enough (with my example above), "Turkish Republic of Northern Cyprus" is also not considered valid since it is not a legal country as per UN resolutions 541/83 and 550/84. So while they are _issued_, they are _invalid_, or just as valid as a "Kingdom of Atlantis" passport according to the EU.

So I guess a distinction should be made as to what is in this repo, and I think it should be passports that are recognised by a majority of UN member states, or at least as per available data. For example Kosovo's independence from Serbia is not recognised by the whole world, only 50%. But it is already in this repo's dataset and EU PRADO list has all but Spain as recognising it.

I think maybe the things NOT on a list such as this might need some manual research. For example, American Samoa is not on the list since it does not issue passports, but if we do a check to see how many territories are in this repo vs. not on the EU's PRADO list, the remainder should (hopefully) not be too long to sift through.

What do you think?

**Comment by mledoze** [comment]
Closing due to lack of time to implement this. Any help is welcome to add this data.
